.TH "evaluar_post_connectar_SSL" 3 "Lunes, 8 de Mayo de 2017" "Version Versión&nbsp;1.2" "Redes de Comunicaciones 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evaluar_post_connectar_SSL \- evaluar_post_connectar_SSL 
Comprueba la seguridad despueés del handshake
.PP
.SS "Synopsis"
.PP
.PP
.nf
#include "includes/G\-2313\-07\-P3\-ConnectionSSL\&.h"

long evaluar_post_connectar_SSL(const SSL *ssl)
.fi
.PP
.PP
.SS "Descripción"
.PP
Esta función comprueba una vez realizado el handshake que el canal de comunicación se puede considerar seguro\&.
.PP
\fBParámetros:\fP
.RS 4
\fIssl\fP Constante de la conexión SSL, no se va a modificar en la función
.RE
.PP
\fBValores devueltos:\fP
.RS 4
\fITRUE\fP la comunicación a través del canal es segura 
.br
\fIFALSE\fP la comunicación a través del canal no es segura
.RE
.PP
.PP
.PP
.SS "Información"
.PP
\fBAutores:\fP
.RS 4
Alfonso Bonilla Trueba (alfonso.bonilla@estudiante.uam.es) 
.PP
Mónica de la Iglesia Martínez (monica.delaiglesia@estudiante.uam.es) 
.RE
.PP
\fBCopyright:\fP
.RS 4
Pareja 7 - Grupo 2313
.RE
.PP
.PP
 
