.TH "inicializar_nivel_SSL" 3 "Lunes, 8 de Mayo de 2017" "Version Versión&nbsp;1.2" "Redes de Comunicaciones 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inicializar_nivel_SSL \- inicializar_nivel_SSL 
Preparación para poder usar la capa SSL
.PP
.SS "Synopsis"
.PP
.PP
.nf
#include "includes/G\-2313\-07\-P3\-ConnectionSSL\&.h"

void inicializar_nivel_SSL()
.fi
.PP
.PP
.SS "Descripción"
.PP
Esta función se encargará de realizar todas las llamadas necesarias para que la aplicación pueda usar la capa segura SSL\&.
.PP
.PP
.PP
.SS "Información"
.PP
\fBAutores:\fP
.RS 4
Alfonso Bonilla Trueba (alfonso.bonilla@estudiante.uam.es) 
.PP
Mónica de la Iglesia Martínez (monica.delaiglesia@estudiante.uam.es) 
.RE
.PP
\fBCopyright:\fP
.RS 4
Pareja 7 - Grupo 2313
.RE
.PP
.PP
 
