.TH "IRCInterface_ActivatePrivate" 3 "Lunes, 8 de Mayo de 2017" "Version Versión&nbsp;1.0" "Redes de Comunicaciones 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRCInterface_ActivatePrivate \- IRCInterface_ActivatePrivate 
Llamada por el botón de activación del modo privado\&.
.PP
.SS "Synopsis"
.PP
.PP
.nf
#include <redes2/ircxchat\&.h>

   void IRCInterface_ActivatePrivate (char *channel)
.fi
.PP
.PP
.SS "Descripción"
.PP
Llamada por el botón de activación del modo privado\&.
.PP
En cualquier caso sólo se puede realizar si el servidor acepta la orden\&. La string recibida no debe ser manipulada por el programador, sólo leída\&.
.PP
\fBParámetros:\fP
.RS 4
\fIchannel\fP canal sobre el que se va a activar la privacidad\&.
.RE
.PP
.PP
.PP
.SS "Información"
.PP
\fBAutores:\fP
.RS 4
Alfonso Bonilla Trueba (alfonso.bonilla@estudiante.uam.es) 
.PP
Mónica de la Iglesia Martínez (monica.delaiglesia@estudiante.uam.es) 
.RE
.PP
\fBCopyright:\fP
.RS 4
Pareja 7 - Grupo 2313
.RE
.PP
.PP
 
