.TH "IRCInterface_StartAudioChat" 3 "Lunes, 8 de Mayo de 2017" "Version Versión&nbsp;1.0" "Redes de Comunicaciones 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRCInterface_StartAudioChat \- IRCInterface_StartAudioChat 
Llamada por el botón 'Iniciar' del diálogo de chat de voz\&.
.PP
.SS "Synopsis"
.PP
.PP
.nf
#include <redes2/ircxchat\&.h>

   void IRCInterface_StartAudioChat (char *nick)
.fi
.PP
.PP
.SS "Descripción"
.PP
Llamada por el botón 'Iniciar' del diálogo de chat de voz\&. Previamente debe seleccionarse un nick del canal para darle voz a dicho usuario\&. Esta función como todos los demás callbacks bloquea el interface y por tanto para mantener la funcionalidad del chat de voz es imprescindible crear un hilo a efectos de comunicación de voz\&.
.PP
En cualquier caso sólo se puede realizar si el servidor acepta la orden\&. La string recibida no debe ser manipulada por el programador, sólo leída\&.
.PP
\fBParámetros:\fP
.RS 4
\fInick\fP nick del usuario con el que se desea conectar\&.
.RE
.PP
\fBValores devueltos:\fP
.RS 4
\fITRUE\fP si se ha establecido la comunicación (debe devolverlo)\&. 
.br
\fIFALSE\fP en caso contrario (debe devolverlo)\&.
.RE
.PP
.PP
.PP
.SS "Información"
.PP
\fBAutores:\fP
.RS 4
Alfonso Bonilla Trueba (alfonso.bonilla@estudiante.uam.es) 
.PP
Mónica de la Iglesia Martínez (monica.delaiglesia@estudiante.uam.es) 
.RE
.PP
\fBCopyright:\fP
.RS 4
Pareja 7 - Grupo 2313
.RE
.PP
.PP
 
