.TH "IRCInterface_ExitAudioChat" 3 "Lunes, 8 de Mayo de 2017" "Version Versión&nbsp;1.0" "Redes de Comunicaciones 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRCInterface_ExitAudioChat \- IRCInterface_ExitAudioChat 
Llamada por el botón 'Cancelar' del diálogo de chat de voz\&.
.PP
.SS "Synopsis"
.PP
.PP
.nf
#include <redes2/ircxchat\&.h>

   void IRCInterface_ExitAudioChat (char *nick)
.fi
.PP
.PP
.SS "Descripción"
.PP
Llamada por el botón 'Parar' del diálogo de chat de voz\&. Previamente debe seleccionarse un nick del canal para darle voz a dicho usuario\&. Esta función cierrala comunicación\&. Evidentemente tiene que actuar sobre el hilo de chat de voz\&.
.PP
En cualquier caso sólo se puede realizar si el servidor acepta la orden\&. La string recibida no debe ser manipulada por el programador, sólo leída\&.
.PP
\fBParámetros:\fP
.RS 4
\fInick\fP nick del usuario que solicita la parada del chat de audio\&.
.RE
.PP
\fBValores devueltos:\fP
.RS 4
\fITRUE\fP si se ha cerrado la comunicación (debe devolverlo)\&. 
.br
\fIFALSE\fP en caso contrario (debe devolverlo)\&.
.RE
.PP
.PP
.PP
.SS "Información"
.PP
\fBAutores:\fP
.RS 4
Alfonso Bonilla Trueba (alfonso.bonilla@estudiante.uam.es) 
.PP
Mónica de la Iglesia Martínez (monica.delaiglesia@estudiante.uam.es) 
.RE
.PP
\fBCopyright:\fP
.RS 4
Pareja 7 - Grupo 2313
.RE
.PP
.PP
 
